### ISSUE TITLE
KIKA Screen doesn't update time

### ISSUE THREAD

**Issue by lordoflife** [skopjehacklab/status.spodeli.org#10]
The screen in Kika doesn't update the Last Open / Open time. 
Stuck on a random number.

**Comment by gdamjan** [comment]
info-panel.html need to be updated to the changes made for index.html

**Comment by gocemitevski** [comment]
https://github.com/skopjehacklab/status.spodeli.org/commit/cfe97446ad9e3a62c1507a639a8d1f9f9d0e9cf1

**Comment by gdamjan** [comment]
works 
![img_20170604_163104](https://cloud.githubusercontent.com/assets/81654/26762604/5d99b2f2-4945-11e7-9e7d-6c8d26ea68e1.jpg)
