### ISSUE TITLE
инфо за сметка

### ISSUE THREAD

**Issue by novica** [skopjehacklab/status.spodeli.org#17]
Дното на страницата status.spodeli.org вели

    Хаклаб КИКА
    ул. Наум Наумовски Борче бр. 38/12, 1000 Скопје
    Сметка: 210057088340110
    Банка: НЛБ Тутунска Скопје

Ако се ова банковните информации за организацијата треба да стои називот и адресата на Слободен софтвер Македонија. Ако е потребно да стои и адресата на хаклабот, тоа треба поинаку да се напише.

**Comment by gdamjan** [comment]
why closed?

**Comment by novica** [comment]
I checked the site and ist implemented.
