### ISSUE TITLE
линк до графана на графиците

### ISSUE THREAD

**Issue by gdamjan** [skopjehacklab/status.spodeli.org#7]
поише истражување на податоците може да се прави на 
http://grafana.softver.org.mk/dashboard/db/hacklab

така да, место refresh, клик на графикот да носи на ова ^

**Comment by gocemitevski** [comment]
@gdamjan или да има посебна иконка, веднаш до таа за refresh, што ќе носи на grafana.softver.org.mk?

Згодно е тоа refresh на клик, ептен.

**Comment by gocemitevski** [comment]
https://github.com/gocemitevski/status.spodeli.org/commit/738f858648021ad9a68e4b56668bc16f14746c50
https://github.com/gocemitevski/status.spodeli.org/commit/990fa08e09455affd296156a9f2e1d1eb21ae858
https://github.com/gocemitevski/status.spodeli.org/commit/7ad9ee8da13b6f9543a3b9cccd3e8666fa26b05a

**Comment by gdamjan** [comment]
што се однесува до експлицитниот refresh јас дури мислам и да се тргне тоа. Доволно е  на 3 минути само да се рефрешира (setTimeout)

**Comment by gocemitevski** [comment]
Па, не е баш јасно дека информациите и графиконите се освежуваат автоматски, кога ќе дојдеш на сајтот. Може и тоа треба некаде да стои напишано.

Јас мислам дека треба да има копчиња за Refresh, дека ја прават страницата поинтерактивна и овозможуваат поголема контрола.

**Comment by gdamjan** [comment]
Генерално не мислам дека страната воопшто треба да биде интерактивна нити да се има некоја контрола. Баш треба пасивна да  биде.

Специфично, рачно кликање refresh нема никаква смисла, имаш две ситуации, 1) доаѓаш на сајтот => информации up-to-date 2) си го заборавил tab-от отворен, се враќаш на него, сакаш up-to-date информации. Графана е за поголема контрола  и интеракција (моеш ко popup iframe да ја ставиш за поинтересно).

И сѐ на сѐ сега има премногу копчиња и интеракција.

**Comment by gocemitevski** [comment]
Што знам... нема интеракција ако не кликаш на ништо... поентата е да ги имаш можностите во случај да сакаш да оствариш интеракција. Исто, не се согласувам дека има премногу копчиња.

> моеш ко popup iframe да ја ставиш за поинтересно

Да кликнеш на графикон и да ти се појави lightbox со содржина од Grafana во iframe?

**Comment by gocemitevski** [comment]
@gdamjan затвори го ова, ако е ок.
